import { addDays, getTodayKey, getWeekNumber, toDateKey } from './date';

const createId = (prefix) =>
  globalThis.crypto?.randomUUID
    ? `${prefix}-${globalThis.crypto.randomUUID()}`
    : `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;

const task = (text, done = false) => ({ id: createId('task'), text, done });

export const createEmptyDailyEntry = (date = getTodayKey()) => ({
  id: createId('day'),
  date,
  missionTasks: [task('', false), task('', false), task('', false)],
  executionNotes: '',
  ideaExploration: '',
  peopleContacted: 0,
  learning: '',
  learningHours: 0,
  deepWorkHours: 0,
  exercise: false,
  smokingCount: 0,
  energyLevel: 5,
  focusLevel: 5,
  winOfDay: '',
  biggestChallenge: '',
  keyInsight: '',
  nextDayPriority: '',
});

export const createEmptyEveningJournal = (date = getTodayKey()) => ({
  id: createId('journal'),
  date,
  progress: '',
  problem: '',
  insight: '',
  waste: '',
  tomorrow: '',
  learning: '',
  gratitude: '',
});

const dailyTemplate = [
  {
    offset: 0,
    missionTasks: [task('Ship updated landing page copy', true), task('Interview 2 supply-chain operators', true), task('Refine onboarding flow metrics', false)],
    executionNotes: 'Shipped homepage proof points and tightened analytics dashboard copy.',
    ideaExploration: 'Operator workflow tooling for regional logistics businesses.',
    peopleContacted: 3,
    learning: 'Read notes on PLG onboarding benchmarks and activation loops.',
    learningHours: 1.4,
    deepWorkHours: 4.6,
    exercise: true,
    smokingCount: 0,
    energyLevel: 8,
    focusLevel: 8,
    winOfDay: 'Two interviewees agreed to pilot the workflow checklist beta.',
    biggestChallenge: 'Ops founders were skeptical about switching from spreadsheets.',
    keyInsight: 'Distribution through implementation partners may beat direct SMB acquisition.',
    nextDayPriority: 'Draft pilot scope and outreach email to implementation partners.',
  },
  {
    offset: 1,
    missionTasks: [task('Map churn reasons from CRM notes', true), task('Write investor update', true), task('Reach out to 3 second-degree intros', true)],
    executionNotes: 'Consolidated churn themes and packaged them into the investor update.',
    ideaExploration: 'Retention tooling for founder-led B2B teams.',
    peopleContacted: 4,
    learning: 'Studied retention levers in vertical SaaS case studies.',
    learningHours: 1.2,
    deepWorkHours: 3.9,
    exercise: true,
    smokingCount: 1,
    energyLevel: 7,
    focusLevel: 7,
    winOfDay: 'Investor update went out with clear asks and metrics.',
    biggestChallenge: 'A few warm intros were stale.',
    keyInsight: 'Operators respond better when the pain is framed as lost margin, not inefficiency.',
    nextDayPriority: 'Package case-study snippets for next outreach wave.',
  },
  {
    offset: 2,
    missionTasks: [task('Outline pricing hypotheses', true), task('Audit analytics instrumentation', false), task('Follow up with pilot prospect', true)],
    executionNotes: 'Rebuilt pricing assumptions and caught missing activation events.',
    ideaExploration: 'Margin intelligence for small distributors.',
    peopleContacted: 2,
    learning: 'Listened to operator podcasts on warehouse labor planning.',
    learningHours: 1.1,
    deepWorkHours: 3.2,
    exercise: false,
    smokingCount: 1,
    energyLevel: 6,
    focusLevel: 7,
    winOfDay: 'Pilot prospect reopened the conversation after seeing mockups.',
    biggestChallenge: 'Instrumentation debt slowed confidence in funnel numbers.',
    keyInsight: 'Buyers want proof that the tool surfaces revenue, not just efficiency.',
    nextDayPriority: 'Patch activation tracking and re-run the funnel.',
  },
  {
    offset: 3,
    missionTasks: [task('Prepare customer interview guide', true), task('Research TAM for distribution niche', true), task('Schedule networking coffee', false)],
    executionNotes: 'Interview guide got sharper around workflow breakdown points.',
    ideaExploration: 'Workflow QA layer for ops-heavy SMBs.',
    peopleContacted: 1,
    learning: 'Read market notes on regional manufacturing digitization.',
    learningHours: 0.8,
    deepWorkHours: 4.1,
    exercise: true,
    smokingCount: 0,
    energyLevel: 8,
    focusLevel: 8,
    winOfDay: 'Interview guide now produces tighter signal.',
    biggestChallenge: 'TAM estimates varied wildly across fragmented markets.',
    keyInsight: 'Narrow niches look small until you map adjacent workflow spend.',
    nextDayPriority: 'Validate TAM assumptions with one operator and one investor.',
  },
  {
    offset: 4,
    missionTasks: [task('Prototype dashboard cards', true), task('Summarize user pain points', true), task('Log founder review notes', true)],
    executionNotes: 'Built a clickable dashboard concept and aligned pain points by severity.',
    ideaExploration: 'Founder dashboard operating system.',
    peopleContacted: 2,
    learning: 'Watched interviews about founder productivity and operating cadence.',
    learningHours: 1.6,
    deepWorkHours: 5.2,
    exercise: true,
    smokingCount: 0,
    energyLevel: 9,
    focusLevel: 9,
    winOfDay: 'Prototype finally felt founder-native instead of generic project management.',
    biggestChallenge: 'Temptation to add too many features early.',
    keyInsight: 'A founder tool must compress signal, not become another inbox.',
    nextDayPriority: 'Cut the roadmap to the smallest meaningful daily loop.',
  },
  {
    offset: 7,
    missionTasks: [task('Rewrite positioning one-liner', true), task('Review notes from 5 prospects', true), task('Block two deep work sessions', true)],
    executionNotes: 'Positioning became far clearer after rewriting around margin recovery.',
    ideaExploration: 'Operations diagnostics for distributors.',
    peopleContacted: 3,
    learning: 'Collected notes from GTM deep dives and operator newsletters.',
    learningHours: 1,
    deepWorkHours: 4.3,
    exercise: true,
    smokingCount: 0,
    energyLevel: 7,
    focusLevel: 8,
    winOfDay: 'One-line positioning became memorable.',
    biggestChallenge: 'Prospects described symptoms differently across sub-industries.',
    keyInsight: 'Unifying language is a product advantage on its own.',
    nextDayPriority: 'Test the new one-liner in outbound messages.',
  },
  {
    offset: 9,
    missionTasks: [task('Audit weekly routines', true), task('Publish founder memo', false), task('Reconnect with dormant advisor', true)],
    executionNotes: 'Reframed routines around output instead of hours spent.',
    ideaExploration: 'Execution systems for solo founders.',
    peopleContacted: 2,
    learning: 'Read about deliberate practice loops for high-performing founders.',
    learningHours: 0.9,
    deepWorkHours: 2.8,
    exercise: false,
    smokingCount: 2,
    energyLevel: 5,
    focusLevel: 6,
    winOfDay: 'Advisor re-engaged and offered intros.',
    biggestChallenge: 'Low energy dragged the afternoon.',
    keyInsight: 'Health habits show up in product quality two days later.',
    nextDayPriority: 'Protect morning focus with a harder cutoff on meetings.',
  },
  {
    offset: 12,
    missionTasks: [task('Analyze founder pain notes', true), task('Sketch an MVP architecture', true), task('Define decision criteria', true)],
    executionNotes: 'Turned messy notes into three product wedges.',
    ideaExploration: 'Founder OS command center.',
    peopleContacted: 1,
    learning: 'Studied second brain workflows and journaling mechanics.',
    learningHours: 1.5,
    deepWorkHours: 4.9,
    exercise: true,
    smokingCount: 0,
    energyLevel: 8,
    focusLevel: 9,
    winOfDay: 'Product wedge became much clearer.',
    biggestChallenge: 'Avoiding over-designed workflows.',
    keyInsight: 'The best operating systems guide behavior through defaults.',
    nextDayPriority: 'Test the command-center framing with peers.',
  },
  {
    offset: 15,
    missionTasks: [task('Call former customer', true), task('Review market maps', true), task('Build outreach list', false)],
    executionNotes: 'Former customer call unlocked a sharper market narrative.',
    ideaExploration: 'Market intelligence loop for vertical SaaS founders.',
    peopleContacted: 3,
    learning: 'Read product teardown notes and GTM essays.',
    learningHours: 1.3,
    deepWorkHours: 3.7,
    exercise: true,
    smokingCount: 1,
    energyLevel: 7,
    focusLevel: 7,
    winOfDay: 'Former customer pointed to an underserved workflow handoff.',
    biggestChallenge: 'Outreach list quality was weaker than expected.',
    keyInsight: 'Good markets often hide inside ignored handoffs.',
    nextDayPriority: 'Qualify outreach targets before volume.',
  },
  {
    offset: 21,
    missionTasks: [task('Review personal operating metrics', true), task('Capture lessons from last sprint', true), task('Set next month goals', true)],
    executionNotes: 'Built a cleaner operating cadence for the next month.',
    ideaExploration: 'Personal OS for founder execution.',
    peopleContacted: 1,
    learning: 'Reflected on execution bottlenecks and journaled patterns.',
    learningHours: 0.7,
    deepWorkHours: 4.0,
    exercise: true,
    smokingCount: 0,
    energyLevel: 8,
    focusLevel: 8,
    winOfDay: 'Next-month operating rhythm is finally coherent.',
    biggestChallenge: 'A few routines were copied from other founders without fit.',
    keyInsight: 'Borrow principles, not routines.',
    nextDayPriority: 'Build around personal constraints instead of founder folklore.',
  },
];

const dailyEntries = dailyTemplate.map((entry) => ({
  id: createId('day'),
  date: toDateKey(addDays(new Date(), -entry.offset)),
  ...entry,
}));

const ideas = [
  {
    id: createId('idea'),
    ideaName: 'MarginPilot',
    problem: 'Regional distributors lose margin because pricing, fulfillment, and exceptions live in disconnected spreadsheets.',
    targetCustomer: 'Founder-led distributors with 20-150 employees',
    marketSize: '$4.2B US vertical software niche',
    whyItMatters: 'A 1-2% margin improvement changes survival for thin-margin operators.',
    existingSolutions: 'ERPs, ad hoc spreadsheets, consulting-heavy ops audits',
    uniqueInsight: 'Operators adopt faster when the product starts as a daily exception board instead of a full ERP replacement.',
    validationScore: 82,
    revenueModel: 'Subscription plus optional implementation',
    difficulty: 'High',
    status: 'Validating',
    nextExperiment: 'Run a paid pilot with two distributors using manual dashboards.',
    createdAt: toDateKey(addDays(new Date(), -12)),
  },
  {
    id: createId('idea'),
    ideaName: 'RelayGraph',
    problem: 'Small B2B founders miss warm intro paths hidden inside loose networks.',
    targetCustomer: 'Seed-stage founders doing founder-led sales',
    marketSize: '$1.1B workflow and CRM adjacency',
    whyItMatters: 'Warm distribution can compress months of slow outbound.',
    existingSolutions: 'LinkedIn, spreadsheets, generic CRMs',
    uniqueInsight: 'Relationship strength + context snippets create better follow-up prompts than connection counts.',
    validationScore: 71,
    revenueModel: 'Subscription per founder seat',
    difficulty: 'Medium',
    status: 'Exploring',
    nextExperiment: 'Prototype relationship graph views from current contact notes.',
    createdAt: toDateKey(addDays(new Date(), -8)),
  },
  {
    id: createId('idea'),
    ideaName: 'Founder OS',
    problem: 'Ambitious founders run on fragmented tools and lose daily execution clarity.',
    targetCustomer: 'Pre-seed and seed founders managing themselves as the core system',
    marketSize: '$900M productivity and founder tooling segment',
    whyItMatters: 'Execution discipline compounds faster than idea quality in the first years.',
    existingSolutions: 'Notion templates, generic task apps, journaling tools',
    uniqueInsight: 'The product should feel like a command center that links execution, learning, health, and network momentum.',
    validationScore: 89,
    revenueModel: 'Subscription with premium analytics templates',
    difficulty: 'Medium',
    status: 'Building',
    nextExperiment: 'Test whether founders return daily for the dashboard loop.',
    createdAt: toDateKey(addDays(new Date(), -3)),
  },
];

const opportunities = [
  {
    id: createId('opp'),
    problem: 'Ops teams struggle to detect margin leakage from manual exception handling.',
    industry: 'Distribution',
    whoExperiencesIt: 'COOs and branch managers',
    evidenceSource: 'Founder interviews and prospect calls',
    frequency: 'Daily',
    marketSize: 'Large',
    opportunityScore: 84,
    potentialSolution: 'Exception inbox with automated margin alerts',
    status: 'Researching',
    createdAt: toDateKey(addDays(new Date(), -6)),
  },
  {
    id: createId('opp'),
    problem: 'Seed founders forget critical follow-ups after networking events and investor meetings.',
    industry: 'Startups',
    whoExperiencesIt: 'Founder-CEOs',
    evidenceSource: 'Personal workflow pain plus peer conversations',
    frequency: 'Weekly',
    marketSize: 'Medium',
    opportunityScore: 76,
    potentialSolution: 'Founder-native CRM with context-driven follow-up prompts',
    status: 'Watching',
    createdAt: toDateKey(addDays(new Date(), -10)),
  },
  {
    id: createId('opp'),
    problem: 'Operator interviews generate rich insight but rarely turn into structured experiments.',
    industry: 'B2B SaaS',
    whoExperiencesIt: 'Pre-product founders',
    evidenceSource: 'Review of past research habits',
    frequency: 'Weekly',
    marketSize: 'Medium',
    opportunityScore: 80,
    potentialSolution: 'Research-to-experiment workflow embedded in the founder dashboard',
    status: 'Pursuing',
    createdAt: toDateKey(addDays(new Date(), -4)),
  },
];

const contacts = [
  {
    id: createId('contact'),
    name: 'Aanya Mehta',
    company: 'Northline Capital',
    industry: 'Venture',
    whereMet: 'Operator dinner in Bengaluru',
    lastContactDate: toDateKey(addDays(new Date(), -5)),
    keyInsight: 'Wants to see repeatable founder habits before leaning into a seed check.',
    followUpDate: toDateKey(addDays(new Date(), 2)),
    relationshipStrength: 'Strategic',
    notes: 'Send concise investor update with pilot metrics.',
    createdAt: toDateKey(addDays(new Date(), -40)),
  },
  {
    id: createId('contact'),
    name: 'Rohan Bedi',
    company: 'FleetForge',
    industry: 'Logistics',
    whereMet: 'Warm intro from previous manager',
    lastContactDate: toDateKey(addDays(new Date(), -3)),
    keyInsight: 'Branch managers waste hours every week reconciling shipment exceptions.',
    followUpDate: toDateKey(addDays(new Date(), 4)),
    relationshipStrength: 'Strong',
    notes: 'Candidate pilot user for MarginPilot.',
    createdAt: toDateKey(addDays(new Date(), -18)),
  },
  {
    id: createId('contact'),
    name: 'Priya Nair',
    company: 'SignalStack',
    industry: 'SaaS',
    whereMet: 'Founder Slack community',
    lastContactDate: toDateKey(addDays(new Date(), -7)),
    keyInsight: 'Shared advice on packaging founder tooling as a daily ritual, not an admin task.',
    followUpDate: toDateKey(addDays(new Date(), 1)),
    relationshipStrength: 'Warm',
    notes: 'Ask for beta feedback on Founder OS dashboard flow.',
    createdAt: toDateKey(addDays(new Date(), -22)),
  },
  {
    id: createId('contact'),
    name: 'Kabir Sethi',
    company: 'FlowRiver',
    industry: 'Operations',
    whereMet: 'Conference breakout session',
    lastContactDate: toDateKey(addDays(new Date(), -9)),
    keyInsight: 'Implementation partners can unlock distribution if the product makes them look smart.',
    followUpDate: toDateKey(addDays(new Date(), 6)),
    relationshipStrength: 'Strategic',
    notes: 'Potential advisor or channel partner.',
    createdAt: toDateKey(addDays(new Date(), -60)),
  },
  {
    id: createId('contact'),
    name: 'Mira Deshpande',
    company: 'OrbitOps',
    industry: 'Manufacturing',
    whereMet: 'Customer interview referral',
    lastContactDate: toDateKey(addDays(new Date(), -1)),
    keyInsight: 'Pain becomes budget when quality misses start hitting revenue.',
    followUpDate: toDateKey(addDays(new Date(), 8)),
    relationshipStrength: 'Strong',
    notes: 'Follow up with mockups after next prototype sprint.',
    createdAt: toDateKey(addDays(new Date(), -14)),
  },
];

const weeklyReviews = [
  {
    id: createId('review'),
    weekNumber: getWeekNumber(addDays(new Date(), -7)),
    biggestProgress: 'Clarified the active idea wedge and lined up two pilot conversations.',
    biggestMistake: 'Let meetings spill into prime deep-work windows.',
    lessonsLearned: 'Signal quality improved once interview questions focused on money lost instead of inconvenience.',
    opportunitiesDiscovered: 'Implementation partners might be the fastest path to distribution.',
    importantContacts: 'Aanya Mehta, Rohan Bedi',
    newSkillsLearned: 'Interview synthesis, lightweight pilot design',
    healthScore: 8,
    focusScore: 7,
    nextWeekStrategy: 'Protect mornings, tighten outbound messaging, and run two prototype walkthroughs.',
    createdAt: toDateKey(addDays(new Date(), -7)),
  },
  {
    id: createId('review'),
    weekNumber: getWeekNumber(addDays(new Date(), -14)),
    biggestProgress: 'Built the first Founder OS dashboard and proved the design direction.',
    biggestMistake: 'Tried to solve too many adjacent workflows in one pass.',
    lessonsLearned: 'A personal operating system needs fewer boxes and stronger defaults.',
    opportunitiesDiscovered: 'Daily execution + networking follow-through is the most painful combination.',
    importantContacts: 'Priya Nair, Kabir Sethi',
    newSkillsLearned: 'Dashboard composition, metric framing',
    healthScore: 7,
    focusScore: 8,
    nextWeekStrategy: 'Ship the dashboard loop and validate daily retention.',
    createdAt: toDateKey(addDays(new Date(), -14)),
  },
];

const decisions = [
  {
    id: createId('decision'),
    decision: 'Focus Founder OS on founder execution instead of generic team productivity.',
    context: 'The product risks becoming a bloated PM tool without a sharper user identity.',
    optionsConsidered: 'Generic PM dashboard, founder command center, investor reporting tool',
    whyChosen: 'Founder execution is a stronger daily loop with clearer emotional urgency.',
    expectedOutcome: 'Higher retention because the product becomes personally indispensable.',
    reviewDate: toDateKey(addDays(new Date(), 14)),
    actualOutcome: '',
    createdAt: toDateKey(addDays(new Date(), -5)),
  },
  {
    id: createId('decision'),
    decision: 'Prioritize daily and weekly operating loops before collaboration features.',
    context: 'The core challenge is personal consistency, not team coordination.',
    optionsConsidered: 'Add team features now, build solo loops first, focus only on analytics',
    whyChosen: 'Solo loops are easier to validate and create the strongest wedge.',
    expectedOutcome: 'Faster MVP and a more coherent founder experience.',
    reviewDate: toDateKey(addDays(new Date(), 21)),
    actualOutcome: '',
    createdAt: toDateKey(addDays(new Date(), -11)),
  },
];

const knowledgeItems = [
  {
    id: createId('knowledge'),
    title: 'Distribution angle > feature list',
    type: 'Insight',
    content: 'The most compelling part of the product is not the dashboard itself, but the way it drives a daily operating ritual.',
    tags: ['product', 'positioning'],
    createdAt: toDateKey(addDays(new Date(), -1)),
  },
  {
    id: createId('knowledge'),
    title: 'Founder-led CRM patterns',
    type: 'Article',
    content: 'Warm relationships outperform volume when follow-up context is captured in the moment.',
    tags: ['networking', 'crm'],
    createdAt: toDateKey(addDays(new Date(), -3)),
  },
  {
    id: createId('knowledge'),
    title: 'Health is a lagging productivity indicator',
    type: 'Startup Lesson',
    content: 'Low-energy days are usually visible in work quality two days later.',
    tags: ['health', 'execution'],
    createdAt: toDateKey(addDays(new Date(), -6)),
  },
  {
    id: createId('knowledge'),
    title: 'Operators buy around margin',
    type: 'Market Observation',
    content: 'Operations leaders open up faster when the conversation starts with lost gross margin.',
    tags: ['market', 'sales'],
    createdAt: toDateKey(addDays(new Date(), -9)),
  },
  {
    id: createId('knowledge'),
    title: 'Mini experiments beat big bets',
    type: 'Idea',
    content: 'Every new feature should be attached to the next experiment instead of a broad roadmap promise.',
    tags: ['experiments', 'focus'],
    createdAt: toDateKey(addDays(new Date(), -12)),
  },
];

const quickNotes = [
  {
    id: createId('capture'),
    type: 'Note',
    text: 'Ask pilot prospects what they already do every Friday to review operations.',
    createdAt: new Date().toISOString(),
  },
  {
    id: createId('capture'),
    type: 'Insight',
    text: 'A founder tool must make momentum visible in under 30 seconds.',
    createdAt: new Date(addDays(new Date(), -2)).toISOString(),
  },
];

const eveningJournals = [
  {
    id: createId('journal'),
    date: toDateKey(addDays(new Date(), -1)),
    progress: 'Closed the loop on investor update and sharpened the onboarding narrative.',
    problem: 'How to make the dashboard feel actionable without adding clutter.',
    insight: 'Clarity comes from ranking decisions, not capturing more data.',
    waste: 'Too much afternoon context switching.',
    tomorrow: 'Protect two 90-minute blocks before any calls.',
    learning: 'Warm outreach works best when it names the specific pain you learned from them.',
    gratitude: 'Grateful for one advisor who keeps pushing for simplicity.',
  },
  {
    id: createId('journal'),
    date: toDateKey(addDays(new Date(), -3)),
    progress: 'Built the first working dashboard skeleton.',
    problem: 'How to balance personal tracking with startup opportunity discovery.',
    insight: 'The dashboard should show compounding systems, not vanity metrics.',
    waste: 'Over-optimizing minor layout choices.',
    tomorrow: 'Ship the interaction flow and test it on one founder.',
    learning: 'Fast design decisions beat endless exploration at this stage.',
    gratitude: 'Grateful for clear early feedback from peers.',
  },
];

export const createSampleData = () =>
  JSON.parse(
    JSON.stringify({
      settings: {
        founderName: 'Shashank',
        theme: 'dark',
      },
      dailyEntries,
      ideas,
      opportunities,
      contacts,
      weeklyReviews,
      decisions,
      knowledgeItems,
      quickNotes,
      eveningJournals,
    }),
  );
