import { addDays, getTodayKey, toDateKey } from './date';

const createId = (prefix) =>
  globalThis.crypto?.randomUUID
    ? `${prefix}-${globalThis.crypto.randomUUID()}`
    : `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;

export const createEmptyStrategicPlan = () => ({
  id: createId('strategy'),
  planName: '',
  horizon: 'Quarterly',
  period: '',
  mission: '',
  northStarMetric: '',
  northStarTarget: '',
  keyResults: '',
  strategicBets: '',
  topPriorities: '',
  risks: '',
  progress: 0,
  confidence: 5,
  status: 'Draft',
  createdAt: getTodayKey(),
});

export const createEmptyCustomerInsight = () => ({
  id: createId('research'),
  company: '',
  contactName: '',
  segment: '',
  interviewDate: getTodayKey(),
  problemArea: '',
  painScore: 7,
  budgetSignal: 5,
  currentWorkflow: '',
  urgency: '',
  objections: '',
  requestedOutcome: '',
  notableQuote: '',
  pmfSignal: 'Emerging',
  nextStep: '',
  createdAt: getTodayKey(),
});

export const createEmptyRevenueItem = () => ({
  id: createId('revenue'),
  accountName: '',
  channelType: 'Lead',
  stage: 'Prospect',
  dealValue: 0,
  closeProbability: 10,
  expectedCloseDate: '',
  source: '',
  useCase: '',
  nextStep: '',
  blockers: '',
  createdAt: getTodayKey(),
});

export const createEmptyFinanceSnapshot = () => ({
  id: createId('finance'),
  snapshotDate: getTodayKey(),
  cashOnHand: 0,
  monthlyRevenue: 0,
  monthlyBurn: 0,
  payroll: 0,
  infraCost: 0,
  marketingSpend: 0,
  otherExpenses: 0,
  targetRunwayMonths: 18,
  notes: '',
  scenarioName: 'Base Case',
  createdAt: getTodayKey(),
});

export const createEmptyBoardItem = () => ({
  id: createId('board'),
  entryType: 'Investor Update',
  title: '',
  contactName: '',
  firm: '',
  stage: '',
  status: 'Draft',
  date: getTodayKey(),
  nextActionDate: '',
  targetRaise: 0,
  checkSize: 0,
  interestLevel: 5,
  keyWins: '',
  metricsSummary: '',
  asks: '',
  notes: '',
  createdAt: getTodayKey(),
});

export const createEmptyProject = () => ({
  id: createId('project'),
  projectName: '',
  area: 'Product',
  stage: 'Backlog',
  linkedPlanId: '',
  objective: '',
  milestone: '',
  nextStep: '',
  blockers: '',
  dueDate: '',
  launchDate: '',
  progress: 0,
  impactScore: 7,
  confidenceScore: 6,
  successMetric: '',
  tags: [],
  notes: '',
  createdAt: getTodayKey(),
});

export const createDefaultInboxAutomations = () => ({
  settings: {
    autoDailyBrief: true,
    autoWeeklyBrief: true,
    dailyBriefTime: '08:00',
    weeklyBriefDay: 'Mon',
    weeklyBriefTime: '08:30',
  },
  briefs: [],
});

export const createSeedUnicornData = () => ({
  strategicPlans: [
    {
      id: createId('strategy'),
      planName: 'Q2 2026 Founder OS Expansion Plan',
      horizon: 'Quarterly',
      period: 'Q2 2026',
      mission: 'Turn Founder OS into a daily control system that reaches product, GTM, finance, and founder execution in one loop.',
      northStarMetric: 'Weekly active founders',
      northStarTarget: '500 WAU',
      keyResults: 'Reach 500 weekly active founders\nConvert 15 design partners into weekly active users\nMaintain 35%+ weekly returning usage\nShip the founder inbox, AI leverage, and scale OS layers',
      strategicBets: 'Own the founder daily operating loop\nUse AI leverage as a wedge into deeper company workflows\nTurn insight capture into decision-quality dashboards',
      topPriorities: 'Finish PMF instrumentation\nRun 12 founder interviews this quarter\nPackage the product for repeatable referrals\nBuild runway and GTM visibility into the inbox',
      risks: 'Feature sprawl could outrun clarity\nLow customer conversation volume would weaken PMF signal\nWeak revenue instrumentation would slow monetization decisions',
      progress: 58,
      confidence: 7,
      status: 'Active',
      createdAt: toDateKey(addDays(new Date(), -18)),
    },
    {
      id: createId('strategy'),
      planName: '2026 Company Direction',
      horizon: 'Annual',
      period: '2026',
      mission: 'Build the operating system ambitious founders use to run themselves and their companies from zero to scale.',
      northStarMetric: 'Paying founder accounts',
      northStarTarget: '150 paid teams',
      keyResults: 'Establish clear PMF signal in one founder segment\nLaunch a monetization path tied to decision and execution leverage\nReach sustainable growth with clear funnel visibility',
      strategicBets: 'Founder-first workflow depth over broad team collaboration\nAI systems as leverage, not novelty\nCompany metrics visible every day, not only in reviews',
      topPriorities: 'Find the best initial customer segment\nProve retention in the command center\nDesign a repeatable GTM motion',
      risks: 'Noisy segment focus\nWeak pricing clarity\nInsufficient revenue rigor',
      progress: 34,
      confidence: 6,
      status: 'At Risk',
      createdAt: toDateKey(addDays(new Date(), -42)),
    },
  ],
  customerResearch: [
    {
      id: createId('research'),
      company: 'FleetForge',
      contactName: 'Rohan Bedi',
      segment: 'Logistics operators',
      interviewDate: toDateKey(addDays(new Date(), -5)),
      problemArea: 'Exception handling and margin leakage',
      painScore: 9,
      budgetSignal: 7,
      currentWorkflow: 'Branch managers reconcile issues across ERP exports, WhatsApp threads, and spreadsheets.',
      urgency: 'High after every week with missed shipments or invoice adjustments.',
      objections: 'Worries about replacing existing ERP workflows too early.',
      requestedOutcome: 'A daily exception board with margin visibility.',
      notableQuote: 'If you show me where margin is leaking this week, I will look at it every Friday.',
      pmfSignal: 'Strong',
      nextStep: 'Send a workflow mockup and define a paid pilot scope.',
      createdAt: toDateKey(addDays(new Date(), -5)),
    },
    {
      id: createId('research'),
      company: 'SignalStack',
      contactName: 'Priya Nair',
      segment: 'Seed-stage SaaS founders',
      interviewDate: toDateKey(addDays(new Date(), -8)),
      problemArea: 'Fragmented founder operating systems',
      painScore: 8,
      budgetSignal: 6,
      currentWorkflow: 'Founders bounce between Notion docs, calendars, task apps, investor updates, and ad hoc notes.',
      urgency: 'High when fundraising or shipping cadence accelerates.',
      objections: 'Does not want another passive dashboard without a daily loop.',
      requestedOutcome: 'A homepage that tells the founder what actually matters today.',
      notableQuote: 'I do not need more storage. I need a system that tells me what not to miss.',
      pmfSignal: 'Strong',
      nextStep: 'Test the inbox and strategy layers with her next week.',
      createdAt: toDateKey(addDays(new Date(), -8)),
    },
    {
      id: createId('research'),
      company: 'OrbitOps',
      contactName: 'Mira Deshpande',
      segment: 'Manufacturing operations',
      interviewDate: toDateKey(addDays(new Date(), -2)),
      problemArea: 'Quality misses create hidden downstream costs',
      painScore: 7,
      budgetSignal: 8,
      currentWorkflow: 'Plant teams review misses manually in meetings without a predictive triage layer.',
      urgency: 'Medium until quality incidents affect customer SLAs.',
      objections: 'Needs credible ROI and simple adoption path.',
      requestedOutcome: 'Prioritized visibility into the highest-risk workflow handoffs.',
      notableQuote: 'Pain turns into budget once one bad week starts touching revenue.',
      pmfSignal: 'Emerging',
      nextStep: 'Quantify the cost of a missed quality event before pitching a workflow.',
      createdAt: toDateKey(addDays(new Date(), -2)),
    },
  ],
  revenuePipeline: [
    {
      id: createId('revenue'),
      accountName: 'FleetForge Pilot',
      channelType: 'Pilot',
      stage: 'Proposal',
      dealValue: 18000,
      closeProbability: 60,
      expectedCloseDate: toDateKey(addDays(new Date(), 14)),
      source: 'Warm operator intro',
      useCase: 'Margin exception workflow pilot',
      nextStep: 'Send pilot proposal and review success metrics.',
      blockers: 'Need clarity on implementation scope.',
      createdAt: toDateKey(addDays(new Date(), -6)),
    },
    {
      id: createId('revenue'),
      accountName: 'Founder OS Design Partner Cohort',
      channelType: 'Lead',
      stage: 'Discovery',
      dealValue: 12000,
      closeProbability: 35,
      expectedCloseDate: toDateKey(addDays(new Date(), 24)),
      source: 'Founder network referrals',
      useCase: 'Daily command center beta',
      nextStep: 'Run three onboarding calls and test the retention loop.',
      blockers: 'Need sharper segmentation before pricing discussions.',
      createdAt: toDateKey(addDays(new Date(), -4)),
    },
    {
      id: createId('revenue'),
      accountName: 'Channel Partner Program',
      channelType: 'Partnership',
      stage: 'Negotiation',
      dealValue: 30000,
      closeProbability: 50,
      expectedCloseDate: toDateKey(addDays(new Date(), 35)),
      source: 'Conference follow-up',
      useCase: 'Distribution through implementation partners',
      nextStep: 'Define partner incentives and shared pipeline process.',
      blockers: 'Need proof that the product makes the partner look smart fast.',
      createdAt: toDateKey(addDays(new Date(), -10)),
    },
    {
      id: createId('revenue'),
      accountName: 'Founders Guild',
      channelType: 'Lead',
      stage: 'Won',
      dealValue: 6000,
      closeProbability: 100,
      expectedCloseDate: toDateKey(addDays(new Date(), -3)),
      source: 'Community referral',
      useCase: 'Founder OS pilot seats',
      nextStep: 'Convert the win into case-study evidence.',
      blockers: '',
      createdAt: toDateKey(addDays(new Date(), -12)),
    },
  ],
  financeSnapshots: [
    {
      id: createId('finance'),
      snapshotDate: toDateKey(addDays(new Date(), -60)),
      cashOnHand: 145000,
      monthlyRevenue: 2500,
      monthlyBurn: 16000,
      payroll: 9000,
      infraCost: 1200,
      marketingSpend: 1800,
      otherExpenses: 4000,
      targetRunwayMonths: 18,
      notes: 'Early founder-mode base case before revenue and partner traction improve.',
      scenarioName: 'Base Case',
      createdAt: toDateKey(addDays(new Date(), -60)),
    },
    {
      id: createId('finance'),
      snapshotDate: toDateKey(addDays(new Date(), -30)),
      cashOnHand: 138000,
      monthlyRevenue: 4800,
      monthlyBurn: 17000,
      payroll: 9200,
      infraCost: 1400,
      marketingSpend: 2100,
      otherExpenses: 4300,
      targetRunwayMonths: 18,
      notes: 'Revenue is improving, but runway still needs active management.',
      scenarioName: 'Base Case',
      createdAt: toDateKey(addDays(new Date(), -30)),
    },
    {
      id: createId('finance'),
      snapshotDate: toDateKey(addDays(new Date(), -2)),
      cashOnHand: 131500,
      monthlyRevenue: 7200,
      monthlyBurn: 17500,
      payroll: 9500,
      infraCost: 1500,
      marketingSpend: 2400,
      otherExpenses: 4100,
      targetRunwayMonths: 18,
      notes: 'The company is buying time, but still needs more revenue compression or cost discipline.',
      scenarioName: 'Base Case',
      createdAt: toDateKey(addDays(new Date(), -2)),
    },
  ],
  boardItems: [
    {
      id: createId('board'),
      entryType: 'Investor Update',
      title: 'March investor update',
      contactName: 'Aanya Mehta',
      firm: 'Northline Capital',
      stage: 'Seed relationship',
      status: 'Draft',
      date: toDateKey(addDays(new Date(), 2)),
      nextActionDate: toDateKey(addDays(new Date(), 2)),
      targetRaise: 0,
      checkSize: 0,
      interestLevel: 8,
      keyWins: 'Founder inbox launched, AI leverage shipped, two founder cohorts actively testing.',
      metricsSummary: 'Weekly active founders rising, first paid cohort closed, AI opportunity library expanding.',
      asks: 'Intro to two operator-heavy SaaS founders and feedback on metrics that would increase conviction.',
      notes: 'Keep the update crisp and metrics-led.',
      createdAt: toDateKey(addDays(new Date(), -4)),
    },
    {
      id: createId('board'),
      entryType: 'Board Meeting',
      title: 'Q2 board prep',
      contactName: 'Kabir Sethi',
      firm: 'Advisor circle',
      stage: 'Advisory review',
      status: 'Scheduled',
      date: toDateKey(addDays(new Date(), 11)),
      nextActionDate: toDateKey(addDays(new Date(), 7)),
      targetRaise: 0,
      checkSize: 0,
      interestLevel: 7,
      keyWins: 'Sharper PMF story, clearer GTM wedge, more founder retention signal.',
      metricsSummary: 'Need runway, pipeline, and PMF charts finalized before review.',
      asks: 'Sanity-check the Q2 strategy and hiring pacing.',
      notes: 'Prepare a clean one-page board narrative.',
      createdAt: toDateKey(addDays(new Date(), -7)),
    },
    {
      id: createId('board'),
      entryType: 'Fundraise',
      title: 'Seed round pipeline',
      contactName: 'Priya Nair',
      firm: 'Angel syndicate',
      stage: 'Relationship building',
      status: 'Open',
      date: toDateKey(addDays(new Date(), -3)),
      nextActionDate: toDateKey(addDays(new Date(), 5)),
      targetRaise: 1500000,
      checkSize: 100000,
      interestLevel: 6,
      keyWins: 'Product scope sharper and operating metrics improving.',
      metricsSummary: 'Need more PMF evidence and a stronger pipeline story before opening broadly.',
      asks: 'Warm introductions after the next founder cohort closes.',
      notes: 'Treat this as a relationship pipeline, not a live process yet.',
      createdAt: toDateKey(addDays(new Date(), -9)),
    },
  ],
  projects: [
    {
      id: createId('project'),
      projectName: 'Founder Inbox Retention Loop',
      area: 'Product',
      stage: 'In Progress',
      linkedPlanId: '',
      objective: 'Make the inbox strong enough to become the daily homepage for founders.',
      milestone: 'Ship daily CEO brief surface and project-driven action ranking.',
      nextStep: 'Test the updated inbox with 5 founders and instrument repeated weekly use.',
      blockers: '',
      dueDate: toDateKey(addDays(new Date(), 10)),
      launchDate: toDateKey(addDays(new Date(), 14)),
      progress: 68,
      impactScore: 9,
      confidenceScore: 7,
      successMetric: '35%+ weekly returning usage',
      tags: ['core-product', 'retention'],
      notes: 'This is the main control point for the whole product.',
      createdAt: toDateKey(addDays(new Date(), -12)),
    },
    {
      id: createId('project'),
      projectName: 'Design Partner GTM Sprint',
      area: 'GTM',
      stage: 'Ready to Launch',
      linkedPlanId: '',
      objective: 'Turn design partner interest into a repeatable founder referral and pilot motion.',
      milestone: 'Launch outreach sequence with a tighter PMF narrative.',
      nextStep: 'Send the next wave of founder and operator invites.',
      blockers: '',
      dueDate: toDateKey(addDays(new Date(), 5)),
      launchDate: toDateKey(addDays(new Date(), 6)),
      progress: 84,
      impactScore: 8,
      confidenceScore: 8,
      successMetric: '10 quality onboarding calls booked',
      tags: ['distribution', 'design-partners'],
      notes: 'This should directly improve customer signal and pipeline quality.',
      createdAt: toDateKey(addDays(new Date(), -8)),
    },
    {
      id: createId('project'),
      projectName: 'Investor Metrics Narrative',
      area: 'Fundraising',
      stage: 'Blocked',
      linkedPlanId: '',
      objective: 'Build a seed-ready metrics story that ties product usage to revenue potential.',
      milestone: 'Finalize one-page investor update template with PMF, pipeline, and runway.',
      nextStep: 'Resolve missing retention and revenue cohort views.',
      blockers: 'Need stronger recurring PMF evidence and cleaner cohort instrumentation.',
      dueDate: toDateKey(addDays(new Date(), 9)),
      launchDate: '',
      progress: 42,
      impactScore: 8,
      confidenceScore: 5,
      successMetric: 'Investors can understand traction in one page',
      tags: ['fundraising', 'metrics'],
      notes: 'This is blocked by instrumentation quality, not design.',
      createdAt: toDateKey(addDays(new Date(), -9)),
    },
  ],
  inboxAutomations: createDefaultInboxAutomations(),
});
